-- Generated by scripts/build-d1-feature-sample.mjs.
-- Values are extracted from src/generated/release-catalog.json.

INSERT INTO releases (release_id, source_release_id, release_date, generated_at, description, storage_layout, hf_repository, hf_revision, release_asset_base_url, manifest_index_path, total_genomes, feature_summary_json)
VALUES ('2026-08-07', NULL, '2026-08-07', '2026-08-07T00:00:00.000Z', 'Two-genome example backed by the RAPPTOR Hugging Face pilot', 'individual-v1', 'liurulong/bacterial-promoter-genomes-pilot', 'main', 'https://huggingface.co/datasets/liurulong/bacterial-promoter-genomes-pilot/resolve/main/releases/2026-08-07', NULL, 2, '{"promoter":{"genomeCount":2,"featureCount":25571}}');

INSERT INTO portal_state (singleton, active_release_id) VALUES (1, '2026-08-07');

INSERT INTO genomes (release_id, accession, organism_name, strain, domain, phylum, class_name, order_name, family, genus, genome_source, assembly_level, genome_size_bp, gc_content, contig_count, completeness, contamination, default_locus, primary_sequence, reference_storage_json) VALUES
('2026-08-07', 'GCA_000411415.1', 'Pauljensenia sp000411415', NULL, 'Bacteria', 'Actinomycetota', 'Actinomycetia', 'Actinomycetales', 'Actinomycetaceae', 'Pauljensenia', 'NCBI GenBank', NULL, 2430444, 65.0233, 3, NULL, NULL, 'KE150450.1:1-10000', 'KE150450.1', '{"layout":"individual-v1","files":{"fasta":"objects/GCA_000411415.1/reference.fa.gz","fai":"objects/GCA_000411415.1/reference.fa.gz.fai","gzi":"objects/GCA_000411415.1/reference.fa.gz.gzi","metadata":"objects/GCA_000411415.1/metadata.json"}}'),
('2026-08-07', 'GCA_000421325.1', 'AAA536-G10 sp000421325', NULL, 'Bacteria', 'Pseudomonadota', 'Alphaproteobacteria', 'Puniceispirillales', 'AAA536-G10', 'AAA536-G10', 'NCBI GenBank', NULL, 1995180, 31.0436, 92, NULL, NULL, 'ATWQ01000001.1:1-10000', 'ATWQ01000001.1', '{"layout":"individual-v1","files":{"fasta":"objects/GCA_000421325.1/reference.fa.gz","fai":"objects/GCA_000421325.1/reference.fa.gz.fai","gzi":"objects/GCA_000421325.1/reference.fa.gz.gzi","metadata":"objects/GCA_000421325.1/metadata.json"}}');

INSERT INTO feature_sets (release_id, accession, feature_type, evidence_type, count_unit, feature_count, status, is_default, source_id, source_version, provenance_json, data_path, index_path, storage_json) VALUES
('2026-08-07', 'GCA_000411415.1', 'promoter', 'prediction', 'peak', 17030, 'ready', 1, 'rapptor', 'unrecorded', '{"catalogRelease":"2026-08-07"}', 'objects/GCA_000411415.1/predicted-promoters.gff3.gz', 'objects/GCA_000411415.1/predicted-promoters.gff3.gz.tbi', '{}'),
('2026-08-07', 'GCA_000421325.1', 'promoter', 'prediction', 'peak', 8541, 'ready', 1, 'rapptor', 'unrecorded', '{"catalogRelease":"2026-08-07"}', 'objects/GCA_000421325.1/predicted-promoters.gff3.gz', 'objects/GCA_000421325.1/predicted-promoters.gff3.gz.tbi', '{}');

INSERT OR IGNORE INTO genome_search_terms (release_id, accession, token) VALUES
('2026-08-07', 'GCA_000411415.1', 'actinomycetaceae'),
('2026-08-07', 'GCA_000411415.1', 'actinomycetales'),
('2026-08-07', 'GCA_000411415.1', 'actinomycetia'),
('2026-08-07', 'GCA_000411415.1', 'actinomycetota'),
('2026-08-07', 'GCA_000411415.1', 'bacteria'),
('2026-08-07', 'GCA_000411415.1', 'gca_000411415.1'),
('2026-08-07', 'GCA_000411415.1', 'pauljensenia'),
('2026-08-07', 'GCA_000411415.1', 'sp000411415'),
('2026-08-07', 'GCA_000421325.1', 'aaa536-g10'),
('2026-08-07', 'GCA_000421325.1', 'alphaproteobacteria'),
('2026-08-07', 'GCA_000421325.1', 'bacteria'),
('2026-08-07', 'GCA_000421325.1', 'gca_000421325.1'),
('2026-08-07', 'GCA_000421325.1', 'pseudomonadota'),
('2026-08-07', 'GCA_000421325.1', 'puniceispirillales'),
('2026-08-07', 'GCA_000421325.1', 'sp000421325');

INSERT OR IGNORE INTO facet_options (release_id, kind, value, domain, phylum, class_name, order_name, family) VALUES
('2026-08-07', 'class', 'Actinomycetia', 'Bacteria', 'Actinomycetota', '', '', ''),
('2026-08-07', 'class', 'Alphaproteobacteria', 'Bacteria', 'Pseudomonadota', '', '', ''),
('2026-08-07', 'domain', 'Bacteria', '', '', '', '', ''),
('2026-08-07', 'family', 'AAA536-G10', 'Bacteria', 'Pseudomonadota', 'Alphaproteobacteria', 'Puniceispirillales', ''),
('2026-08-07', 'family', 'Actinomycetaceae', 'Bacteria', 'Actinomycetota', 'Actinomycetia', 'Actinomycetales', ''),
('2026-08-07', 'genus', 'AAA536-G10', 'Bacteria', 'Pseudomonadota', 'Alphaproteobacteria', 'Puniceispirillales', 'AAA536-G10'),
('2026-08-07', 'genus', 'Pauljensenia', 'Bacteria', 'Actinomycetota', 'Actinomycetia', 'Actinomycetales', 'Actinomycetaceae'),
('2026-08-07', 'order', 'Actinomycetales', 'Bacteria', 'Actinomycetota', 'Actinomycetia', '', ''),
('2026-08-07', 'order', 'Puniceispirillales', 'Bacteria', 'Pseudomonadota', 'Alphaproteobacteria', '', ''),
('2026-08-07', 'phylum', 'Actinomycetota', 'Bacteria', '', '', '', ''),
('2026-08-07', 'phylum', 'Pseudomonadota', 'Bacteria', '', '', '', ''),
('2026-08-07', 'source', 'NCBI GenBank', '', '', '', '', '');
